version: '3.1'

services:
  nxplx-database:
    image: postgres:13-alpine
    environment:
      - POSTGRES_PASSWORD=dev
    ports:
      - "5432:5432"
      
  nxplx-cache:
    image: redis:6-alpine
    command: redis-server --requirepass dev
    ports:
      - "6379:6379"

  nxplx-logs:
    image: datalust/seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5342:80"
      - "5341:5341"