name: CI

on:
  pull_request:
    branches:
      - master
    paths:
    - 'nxplx-backend/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      working-directory: ./nxplx-backend
    timeout-minutes: 10
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Prepare .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Test with dotnet
      run: dotnet test NxPlx.sln --logger GitHubActions