name: CI - SonarScan
on:
  push:
    branches:
      - master
    paths:
    - 'nxplx-backend/**'
    - 'nxplx-frontend/**'
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened]
    paths:
    - 'nxplx-backend/**'
    - 'nxplx-frontend/**'

name: Sonar scan
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Cancel outdated workflow-runs
      uses: fkirc/skip-duplicate-actions@master

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
